Ran model over various areas, ending with globally. It worked, and was much faster than last time. Haven't checked results at all, including for missing output chunks (which was a problem last time).
Made some changes that should improve speed:
Data type for each input layer is determined before tasks are created, so only done once, rather than on every chunk. That was quite redundant, since all chunks for a given input have the same datatype.
That meant that when input chunks are being downloaded, if a specific input doesn't exist for that chunk, a numpy array of the correct size and datatype that is all 0s could be created. This meant I didn't need to have a later step of going back through all the inputs are creating numpy arrays of the right datatype for all inputs.
I fixed a problem with the function that checks if any/all required inputs exist. It wasn't working right and was letting chunks get through that didn't have data in them. So, there were a bunch of chunks being analyzed before that shouldn't've been analyzed. I think that's fixed now, although some other issue could emerge.

python -m scripts.utilities.create_cluster -n 40 -m 16 -c 2
For the two larger areas, waited for 38 or more workers to be available before starting:
python -m scripts.core_model.LULUCF_fluxes -cn AFOLU_flux_model_scripts -bb 10 40 20 50 -cs 1
10x10 (100 chunks): 4:53, 13 credits, $0.42 AWS (2.93 seconds/chunk)

python -m scripts.core_model.LULUCF_fluxes -cn AFOLU_flux_model_scripts -bb 10 35 25 50 -cs 1
15x15 (225 chunks): 7:08, 11.5 credits, $0.38 AWS (1.90 seconds/chunk)

python -m scripts.core_model.LULUCF_fluxes -cn AFOLU_flux_model_scripts -bb 10 30 30 50 -cs 1
20x20 (400 chunks): 9:17, 19.00 credits, $0.60 AWS (1.4 seconds/chunk)

Using only improvements 1 and 2 above (so, outputs for all chunks, even if no data):
python -m scripts.core_model.LULUCF_fluxes -cn AFOLU_flux_model_scripts -bb 10 20 40 50 -cs 1
30x30 (900 chunks): 21:18, 35 credits, $1.20 AWS (1.42 seconds/chunk)

Using all three improvements above:
python -m scripts.core_model.LULUCF_fluxes -cn AFOLU_flux_model_scripts -bb 10 20 40 50 -cs 1
30x30 (900 chunks): 17:25, 31,5 credits, $1.00 AWS (1.16 seconds/chunk)

Doing another global run. Main changes since last global run: 1) speed improvements in Comment by David Gibbs on Computing performance/benchmarking record, 2) added non-CO2 emissions placeholder, 3) added gain year count output to some parts of tree, and 4) completed basic complete version of tree (all branches covered).

python -m scripts.utilities.create_cluster -n 40 -m 16 -c 2
For the two larger areas, waited for 36 or more workers to be available before starting (just takes too long to get to 38, my previous threshold):
python -m scripts.core_model.LULUCF_fluxes -cn AFOLU_flux_model_scripts -bb 10 40 20 50 -cs 1
10x10 (100 chunks): 4:55, 12.5 credits, $0.41 AWS (2.95 seconds/chunk)

python -m scripts.core_model.LULUCF_fluxes -cn AFOLU_flux_model_scripts -bb 10 35 25 50 -cs 1
15x15 (225 chunks): 6:29, [didn't record] credits, <$0.60 AWS (1.72 seconds/chunk)

python -m scripts.core_model.LULUCF_fluxes -cn AFOLU_flux_model_scripts -bb 10 30 30 50 -cs 1
20x20 (400 chunks): 9:28, 19 credits, $0.60 AWS (1.42 seconds/chunk)

python -m scripts.core_model.LULUCF_fluxes -cn AFOLU_flux_model_scripts -bb 10 20 40 50 -cs 1
30x30 (900 chunks): 17:00, 28 credits, $0.90 AWS (1.13 seconds/chunk)

Successful global run:
python -m scripts.utilities.create_cluster -n 200 -m 16 -c 2
python -m scripts.core_model.LULUCF_fluxes -cn AFOLU_flux_model_scripts -bb -180 -60 180 80 -cs 1
All 200 workers stayed (didn't lose any), and it ended with exactly the right number of tasks (50,400) (it didn't have to retry tasks). It took about 1 hours 45 minutes, used about 670 Coiled credits (when it finished all tasks, before stats and log, and cost about $21 on AWS (also just after it finished tasks).

The chunk stats spreadsheet was too many rows for Excel, so it threw an error and never created the spreadsheet, nor created the log.
Message was:
Skipped chunk 178_79_179_80 because of a lack of data: 20240927_14_42_39
Skipped chunk 179_79_180_80 because of a lack of data: 20240927_14_33_48
Number of 'Success' chunks: 16338
Number of 'Skipped' chunks: 34062
Difference between submitted chunks and processed chunks: 0
Calculating tile stats...
Traceback (most recent call last):
  File "/mnt/c/GIS/git/AFOLU_GHG_flux_model/src/LULUCF/scripts/utilities/universal_utilities.py", line 702, in calculate_chunk_stats
    sorted_stats.to_excel(writer, sheet_name='chunk_stats', index=False)
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/pandas/core/generic.py", line 2417, in to_excel
    formatter.write(
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/pandas/io/formats/excel.py", line 931, in write
    raise ValueError(
ValueError: This sheet is too large! Your sheet size is: 1797180, 8 Max sheet size is: 1048576, 16384

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/c/GIS/git/AFOLU_GHG_flux_model/src/LULUCF/scripts/core_model/LULUCF_fluxes.py", line 898, in <module>
    main(args.cluster_name, args.bounding_box, args.chunk_size, args.run_local, args.no_stats, args.no_log, args.no_upload)
  File "/mnt/c/GIS/git/AFOLU_GHG_flux_model/src/LULUCF/scripts/core_model/LULUCF_fluxes.py", line 868, in main
    uu.calculate_chunk_stats(all_stats, stage)
  File "/mnt/c/GIS/git/AFOLU_GHG_flux_model/src/LULUCF/scripts/utilities/universal_utilities.py", line 701, in calculate_chunk_stats
    with pd.ExcelWriter(f'{cn.chunk_stats_path}{stage}_chunk_statistics_{timestr()}.xlsx') as writer:
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1353, in __exit__
    self.close()
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1357, in close
    self._save()
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 110, in _save
    self.book.save(self._handles.handle)
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/openpyxl/workbook/workbook.py", line 386, in save
    save_workbook(self, filename)
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 304, in save_workbook
    writer.save()
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 286, in save
    self.write_data()
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 100, in write_data
    archive.writestr(ARC_WORKBOOK, writer.write())
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 150, in write
    self.write_views()
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 137, in write_views
    active = get_active_sheet(self.wb)
  File "/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 35, in get_active_sheet
    raise IndexError("At least one sheet must be visible")
IndexError: At least one sheet must be visible

Also, this happened but it still ran fine. Took about 4-5 minutes to get from task creation to the first routine message after:
Creating tasks and starting processing: 20240927_12_21_09
/home/dagibbs22/anaconda3/envs/updated_Coiled/lib/python3.10/site-packages/distributed/client.py:3163: UserWarning: Sending large graph of size 77.22 MiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
  warnings.warn(